### ISSUE TITLE
Build 3083, AttributeError: 'NoneType' object has no attribute 'is_enabled'

### ISSUE THREAD

**Issue by Centril** [facelessuser/ScopeHunter#22]
On Sublime Text build 3083 I'm getting `<see below>` every time I toggle instant scoper:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "scope_hunter in C:\Users\twing\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 622, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "scope_hunter in C:\Users\twing\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 622, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 520, in run_
    return self.run()
  File "scope_hunter in C:\Users\twing\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 591, in run
AttributeError: 'NoneType' object has no attribute 'instant_scoper'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "scope_hunter in C:\Users\twing\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 622, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "scope_hunter in C:\Users\twing\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 622, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'is_enabled'
```

**Comment by facelessuser** [comment]
Are you sure you don't need to just restart Sublime after installing.  I am on 3095 with no issues.  If restarting isn't helping, I will need to know what Color Scheme are you using and where I can find it to make sure there isn't a parsing issue, but from the error you are showing, I doubt that is the issue.  I imagine you need to restart Sublime Text.

**Comment by Centril** [comment]
Restarted a couple of times now - no difference... Color Scheme is: https://github.com/lefoy/cyanide-theme/blob/master/Monocyanide.tmTheme

**Comment by facelessuser** [comment]
In the future, always scan your entire log for errors.  What you posted was just the symptom of an earlier error:

```
ScopeHunter: Theme parsing failed!  Ingoring theme related info.
Traceback (most recent call last):
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\scope_hunter.py", line 799, in init_color_scheme
    scheme_matcher = ColorSchemeMatcher(scheme_file)
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\lib\color_scheme_matcher.py", line 80, in __init__
    readPlistFromBytes(sublime.load_binary_resource(sublime_format_path(self.color_scheme)))
  File "./plistlib.py", line 104, in readPlistFromBytes
  File "./plistlib.py", line 76, in readPlist
  File "./plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 23, column 0

Traceback (most recent call last):
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\scope_hunter.py", line 809, in reinit_plugin
    sh_theme.setup()
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\scope_hunter.py", line 784, in setup
    theme_file = 'dark' if scheme_matcher.is_dark_theme else 'light'
AttributeError: 'NoneType' object has no attribute 'is_dark_theme'
reloading Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
ScopeHunter: Theme parsing failed!  Ingoring theme related info.
Traceback (most recent call last):
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\scope_hunter.py", line 799, in init_color_scheme
    scheme_matcher = ColorSchemeMatcher(scheme_file)
  File "C:\Users\muse_i\AppData\Roaming\Sublime Text 3\Packages\ScopeHunter\lib\color_scheme_matcher.py", line 80, in __init__
    readPlistFromBytes(sublime.load_binary_resource(sublime_format_path(self.color_scheme)))
  File "./plistlib.py", line 104, in readPlistFromBytes
  File "./plistlib.py", line 76, in readPlist
  File "./plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 23, column 0
```

What this means is Pythons xml parser is chocking on parsing the Monocyanide theme.  Why is this?  Well it's because the author of that file failed to put the version encoding deceleration on the first line `<?xml version="1.0" encoding="UTF-8"?>`.  This should always be the first line.  It is the first so that the file can be parsed quickly so that the encoding can be determined before reading the file's content.  Instead, Monocyanide puts a bunch of comments first.  This defeats the purpose of having the encoding written in the file.  How does the parser know how deep into the file to read to get the encoding?  It's not supposed guess, it's supposed to be the first line.  So it is likely the parser could start reading comment data in some unexpected encoding and cause an error. So my advice is to get Monocyanide to fix their xml or fix it locally for yourself.

**Comment by facelessuser** [comment]
@Centril, I am going to assume you got this message, as the issue is with your theme, there is nothing more I can do.  Hope you get it resolved.

**Comment by Centril** [comment]
Yes, sorry for not replying, thanks!

**Comment by facelessuser** [comment]
Looks like I am going to start stripping comments.  So even though comments should not be first in an XML, scopehunter will strip them in the future.  This is mainly because scopehunter chokes on comments  with dashes like: `<!-- comment ------ -->`.  This is more an `xml.parser.expat` issue, but it is just easier to strip them out.
